import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";
import { BookingProvider } from "@/context/BookingContext";

export const metadata: Metadata = {
  title: "njoyHolidayz - Best Travel Expreince",
  description: "Generated by njoyHolidayz app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <BookingProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </BookingProvider>
      </body>
    </html>
  );
}

